[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@solmate=lib/solmate/src"
]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
[profile.ci]
src = "src"
out = "out"
libs = ["lib"]

[fuzz]
runs = 20

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
multiline_func_header = "attributes_first"
ignore = ["lib/**"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
